# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

google: &google
google_account: <%= ENV["PUNSKER_GOOGLE_ACCOUNT"] %>
google_password: <%= ENV["PUNSKER_GOOGLE_PASSWORD"] %>

twitter: &twitter
  twitter_consumer_key: <%= ENV["PUNSKER_TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["PUNSKER_TWITTER_CONSUMER_SECRET"] %>

facebook: &facebook
  facebook_app_id: <%= ENV["PUNSKER_FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["PUNSKER_FACEBOOK_APP_SECRET"] %>
   
development:
  secret_key_base: e442be4839dfbc31b043ed48cc71f3ebda6503e5e1c8d09c995bac73f45b09aec31f40eaee03fea702cf2fac4f931f8015570bd9063e8291999453333baffd24
  <<: *twitter
  <<: *facebook

test:
  secret_key_base: 83dcae588c2188e847a9168bbe9b05d3dfee2253aeee26dc46514672f44dbf99f2c7638bc35b24f23c4d85a66358ea705cf226e7cfec76ffaf29a33b2f63f461
  <<: *twitter
  <<: *facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *twitter
  <<: *facebook
